version: 2.1
jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
workflows:
  version: 2
  deploy:
    jobs:
      - terraform:
          filters:
            branches:
              only:
                - master
